### ISSUE TITLE
Various Functions Not Working

### ISSUE THREAD

**Issue by usica** [Dancephy/Mixxx-Pioneer-DDJ-SB3#11]
Running Mixxx 2.2.1.
Upon enabling controller get a cascade of error messages.
Press play button: Uncaught exception at line 1 in passed code: TypeError: Result of expression 'PioneerDDJSB3.deck[1]' [undefined] is not an object.
Press pad 1: Uncaught exception at line 1 in passed code: TypeError: Result of expression '(PioneerDDJSB3.hotCuePads)' [undefined] is not a function.

Otherwise, certain things do effect mixxx(browse wheel), but most do nothing except raise an error.

**Comment by TheCultLeader666** [comment]
First of all, you aren't on the latest version of mixxx? (2.2.4)
Second of all, I have also had this problem.

**Comment by usica** [comment]
According to the xml file it would seem it should work even in 2.2.1(see below), but if you're also having the issue in 2.2.4 there must be a different cause.
<MixxxControllerPreset schemaVersion="1" mixxxVersion="2.2+">

**Comment by usica** [comment]
I installed 2.2.4, still doesn't work.

**Comment by jvilalta** [comment]
That's an issue with the release itself. The tag is incorrect in that version, it should state 2.3. The JS interpreter was upgraded for 2.3. Any chance you can upgrade to 2.3?

Sorry for the late response.

**Comment by jevilalta** [comment]
I've created release 2.0.0, which fixes the issue. You can use the on, but you'll need to upgrade to Mixxx 2.3
