### ISSUE TITLE
Mapping for controller "DDJ-SB3----_4" not working properly

### ISSUE THREAD

**Issue by njtwiseman** [Dancephy/Mixxx-Pioneer-DDJ-SB3#13]
Hi Everyone!

Mixxx 2.3.0 (HEAD)
Monday, June 28, 2021 1:04:59 PM

Generates this error on startup

```
Uncaught exception at line 257 in file C:/Users/nick-win/AppData/Local/Mixxx/controllers/Pioneer-DDJ-SB3-scripts.js.

Exception:
  TypeError: Result of expression 'midi.sendSysexMsg' [undefined] is not a function.

Backtrace:
  <anonymous>('DDJ-SB3 ----_4', false) at C:/..../AppData/Local/Mixxx/controllers/Pioneer-DDJ-SB3-scripts.js:257
  <global>() at -1
  ```
  
  I'm planning on taking a look but some direction might be helpful too!

**Comment by njtwiseman** [comment]
So far it looks like the midi.js file isn't being loaded correctly.

When copied directly into the `Pioneer-DDJ-SB3-scritps.js` file
it claims a syntax error on this line
./midi.js:8j
`      console.log(msg.map(byte => "0x" + byte.toString(16).padStart(2, "0")).join(" "));`

**Comment by jvilalta** [comment]
Which version of the script are you using? From the release?

**Comment by njtwiseman** [comment]
I'm on master

**Comment by jevilalta** [comment]
Do you know which version of the controller firmware you are using? The latest version seems to have broken some things. This explains how to check:
https://www.pioneerdj.com/-/media/pioneerdj/downloads/firmwares/controllers/ddj-sb3/ddj-sb3_update_guide_e_1st.pdf

**Comment by jevilalta** [comment]
Turns out the issue is with the controller firmware itself. In order to get decks 3 and 4 to work you must set the output to use the DDJ line out. Otherwise, decks 3 and 4 won't work.

**Comment by bchr** [comment]
It seems they stopped using MIDI channel 3/4 & 10/11 at some point
v1: https://www.pioneerdj.com/-/media/pioneerdj/software-info/controller/ddj-sb3/ddj-sb3_midi_message_list_e1.pdf
v2: https://www.pioneerdj.com/-/media/pioneerdj/software-info/controller/ddj-sb3/ddj-sb3_midi_message_list_e2.pdf

No further info in their changelog
https://www.pioneerdj.com/-/media/pioneerdj/downloads/firmwares/controllers/ddj-sb3/ddj-sb3-firmware-change-history-ver103-en.pdf
