### ISSUE TITLE
Hotcue and FX knob behaviour

### ISSUE THREAD

**Issue by cufito** [Dancephy/Mixxx-Pioneer-DDJ-SB3#17]
Hi, first off I wanted to thank you for the great mapping! It's been really useful, but I wanted to know what I can do to be able to ignore the functions of the pads that aren't hotcues (go to beginning of track, etc.), so I can use all 8 as hotcues and still be able to delete them while pressing shift. I also wanted to know if it was possible to make the FX knob afffect all 3 FX values when no single one is selected for tweaking, as opposed to the fx crossfade.

I've tried tweaking the script and the midi assignments but haven't been able to get it working correctly as I'm not experienced in javascript or mixxx's code inside the MIDI assignment window.

Again, thank you so much!

**Comment by jevilalta** [comment]
Hi

This mapping has been accepted into the Mixxx main project. The mapping there uses 8 hotcues. You can get the files from: https://github.com/mixxxdj/mixxx/tree/2.3/res/controllers or wait for the 2.3.2 release.

**Comment by cufito** [comment]
Thanks! I'll try that
