### ISSUE TITLE
Is this still a thing?

### ISSUE THREAD

**Issue by TheCultLeader666** [Dancephy/Mixxx-Pioneer-DDJ-SB3#4]
I was just wondering about the current status of this project

**Comment by jvilalta** [comment]
The mapping works as described in the readme. This fork is a few commits ahead and might provide more of the features you're looking for: https://github.com/julia-otran/Mixxx-Pioneer-DDJ-SB3. I see others have forked that again but didn't check what has changed. One of those forks might work better for you. 

Mixxx is changing their JS mapping engine so likely very little work will happen here until that has been defined. 

I'm happy to merge any pull requests in if any of the folks on the branches would like to create a PR but haven't seen any requests come through.

**Comment by TheCultLeader666** [comment]
Yeah, I've tried the julia-oltran fork, crucial parts don't seem to work, including playback controls, and I see no way of submitting issues

**Comment by jvilalta** [comment]
FWIW, you're welcome to enter any issues here.

**Comment by TheCultLeader666** [comment]
Ok, I'm probably gonna just mention in an issue here: @julia-oltran

**Comment by TheCultLeader666** [comment]
I'm closing this as there was just an update to the [julia-otran fork](https://github.com/julia-otran/Mixxx-Pioneer-DDJ-SB3) that appears to have gotten every feature working
