### ISSUE TITLE
Auto and manual loop not working

### ISSUE THREAD

**Issue by TylerCousins** [Dancephy/Mixxx-Pioneer-DDJ-SB3#9]
Its not working at all

**Comment by TheCultLeader666** [comment]
Working for me, have you updated to the new version?

**Comment by jevilalta** [comment]
I'm not able to reproduce this either. What version of Mixxx are you using?

**Comment by TylerCousins** [comment]
latest version

**Comment by TheCultLeader666** [comment]
2.2.4 or 2.3? Also, have you updated your mappings to v1.0?
